name: Scala CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Start SBT server
      run: sbt scalafmtSbtCheck scalafmtCheckAll "scalafixAll --check" clean compile Test/compile test
